server:
  port: 8082

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true 
    service-url:
      default-zone: http://localhost:8080/eureka
  instance:
    instance-id: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: producto
          uri: lb://producto
          predicates:
            - Path=/productos/**
